### ISSUE TITLE
error  in ./node_modules/@loadable/component/dist/loadable.esm.mjs

### ISSUE THREAD

**Issue by ZhangDubhe** [gregberge/loadable-components#990] opened 2023-12-19 13:16 UTC
## 🐛 Bug Report
`Can't import the named export 'isValidElementType' from non EcmaScript module (only default export is available)`

## version
5.16.2

**Comment by yofine** [comment] 2023-12-20 06:23
same problem

webpack 4

**Comment by theKashey** [comment] 2023-12-20 11:14
This is related to https://github.com/gregberge/loadable-components/pull/989, reason unknown
- this line `https://github.com/gregberge/loadable-components/blob/2210bcf43b0106776a872541f57afca1f3569491/packages/component/src/createLoadable.js#L3C35-L3C35` got transpired in a little different way, ie it became `import { isValidElementType } from 'react-is';` instead of `import * as ReactIs from 'react-is';

Please fallback to version 5.16.1

**Comment by stevegacka** [comment] 2023-12-25 14:52
I encountered same issue, with Webpack 4. 

Falling back to **5.15.x** of loadable packages resolved for me. NPM reported no 5.16.1 candiate for @loadable/component.

    "@loadable/babel-plugin": "5.15.3",
    "@loadable/component": "5.15.3",
    "@loadable/server": "5.15.3",
    "@loadable/webpack-plugin": "5.15.2",

**Comment by theKashey** [comment] 2023-12-26 04:08
Correct, [5.15.3](https://www.npmjs.com/package/@loadable/component/v/5.15.3) was the previous version.

**Comment by theKashey** [comment] 2023-12-26 04:51
[5.16.3](https://github.com/gregberge/loadable-components/commit/8f40762051ba71a75a378af0030e5614d7daf6e3) has been released with the fix.

**Comment by theKashey** [comment] 2023-12-27 23:39
👋 Can someone confirm that the issue is no longer present so I can close the problem? 🙏

**Comment by stevegacka** [comment] 2023-12-28 21:23
@theKashey 5.16.3 resolved the issue for me! Thank you 🙏

**Comment by theKashey** [comment] 2023-12-29 03:01
🚀

**Closed by theKashey** 2023-12-29 03:01 UTC
