### ISSUE TITLE
Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it

### ISSUE THREAD

**Issue by 1846689910** [gregberge/loadable-components#488] opened 2019-12-21 07:33 UTC
## 💬 Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it

Hi Loadable Components Team,

I have a react project which is ejected from a create-react-app. Now I want to add dynamic import to this project. After following the server side rendering doc in loadable-components, I start the server, and it gives the error 
```
Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it
```
I am sure that I have this plugin installed and put in `.babelrc`. And I did not use typescript in my project.

## codebase
please check my [`dev` branch](https://github.com/1846689910/type-18-hek/tree/dev)
and the [PR](https://github.com/1846689910/type-18-hek/pull/16) for my changes 

## reproduce steps:
1. please clone and check to the [`dev` branch](https://github.com/1846689910/type-18-hek/tree/dev)
2. `npm install`
3. `npm run express`
4. visit http://localhost:3000

**Comment by theKashey** [comment] 2019-12-30 21:44
Duplicate of #466

**Closed by theKashey** 2019-12-30 21:44 UTC
