### ISSUE TITLE
TypeError: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by lfantone** [gregberge/loadable-components#474] opened 2019-12-05 16:44 UTC
## 💥 Regression Report

The latest version of the @loadable/babel-plugin change the way that the plugin creates the loadable component and while creating the content in the server-side throwing:
```
TypeError: Cannot read property 'resolve' of undefined
```

 **now**

```js
const HomeContainerLoader = /* #__LOADABLE__ */ () =>
  import(/* webpackChunkName: "home" */ './pages/HomeContainer/HomeContainer.page');
```

```js
var HomeContainerLoader = {
  resolved: {},
  chunkName: function chunkName() {
    return "home";
  },
  isReady: function isReady(props) {
    var key = this.resolve(props);

    if (this.resolved[key] === false) {
      return false;
    }

    if (true) {
      return !!__webpack_require__.m[key];
    }

    return false;
  },
  importAsync: function importAsync() {
    return Promise.resolve(/*! import() | home */).then(__webpack_require__.bind(null, /*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx"));
  },
  requireAsync: function requireAsync(props) {
    var _this = this;

    var key = this.resolve(props);
    this.resolved[key] = false;
    return this.importAsync(props).then(function (resolved) {
      _this.resolved[key] = true;
      return resolved;
    });
  },
  requireSync: function requireSync(props) {
    var id = this.resolve(props);

    if (true) {
      return __webpack_require__(id);
    }

    return eval('module.require')(id);
  },
  resolve: function resolve() {
    if (true) {
      return /*require.resolve*/(/*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx");
    }

    return eval('require.resolve')("./pages/HomeContainer/HomeContainer.page");
  }
};
```

**Before**

```js
const HomeContainerLoader = /* #__LOADABLE__ */ () =>
  import(/* webpackChunkName: "home" */ './pages/HomeContainer/HomeContainer.page');
```

```js
var HomeContainerLoader = {
  chunkName: function chunkName() {
    return "home";
  },
  isReady: function isReady(props) {
    if (true) {
      return !!__webpack_require__.m[this.resolve(props)];
    }

    return false;
  },
  requireAsync: function requireAsync() {
    return Promise.resolve(/*! import() | home */).then(__webpack_require__.bind(null, /*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx"));
  },
  requireSync: function requireSync(props) {
    var id = this.resolve(props);

    if (true) {
      return __webpack_require__(id);
    }

    return eval('module.require')(id);
  },
  resolve: function resolve() {
    if (true) {
      return /*require.resolve*/(/*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx");
    }

    return eval('require.resolve')("./pages/HomeContainer/HomeContainer.page");
  }
};
```

The issue lives inside the `requireSync` function where the `this` is not defined, replacing directly with
```js
var id = /*require.resolve*/(/*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx");
```
will make this working again.
Also not sure why is passing the `props` to the `resolve` function as is not expecting any arguments.

## Last working version

Worked up to version: 5.10.2

Stopped working in version: 5.11.0 (latest)

## To Reproduce

 1. Install latest `@loadable/babel-plugin` on any project.

## Expected behavior

The server-side content should be generated without any issue.

## Link to repl or repo (highly encouraged)

Will try to upload one tonight.

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 1.46 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.16.3 - /usr/local/bin/node
 - Yarn: 1.19.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.npm-packages/bin/npm
## npmPackages:
 - @loadable/babel-plugin: 5.10.2 => 5.10.3
 - @loadable/component: ^5.11.0 => 5.11.0
 - @loadable/server: ^5.11.0 => 5.11.0
 - @loadable/webpack-plugin: ^5.11.0 => 5.7.1
```

**Comment by theKashey** [comment] 2019-12-05 21:14
Looking...

**Comment by theKashey** [comment] 2019-12-05 21:26
Look like this is not about `this `, but about `require` in `require.resolve`.
Introduced in https://github.com/smooth-code/loadable-components/pull/457

**Comment by theKashey** [comment] 2019-12-05 21:34
- I've reviewed changes and can't tell what's wrong.
- working for SSR example
- duplicate of #471, @bertho-zero - what was your problem, how you fixed it?

**Comment by gregberge** [comment] 2019-12-06 09:31
@theKashey we should avoid using "this" but it requires to change the whole babel generation. `this` should be avoided every time.

**Comment by bertho-zero** [comment] 2019-12-06 10:39
```js
//loadable.js
import loadable from '@loadable/component';

export default (fn, options) => {
  const Component = loadable(fn, options);

  Component.load = (fn.requireAsync || fn).bind(fn); // `.bind` was missing here

  Component.isReady = fn.isReady ? fn.isReady.bind(fn) : (() => false);

  return Component;
};
```

Now that a `.load` and `.isReady` method exists this wrapper may not be useful anymore.

**Comment by lfantone** [comment] 2019-12-06 15:40
It didn't see that is duplicated, sorry for creating a new.

Anyway doing an explicit binding is not the right solution, thought
Anything I can help with? Maybe creating a branch with this issue, let me know.

**Comment by bertho-zero** [comment] 2019-12-06 15:49
@lfantone Do you directly use `@loadable/component` or a wrapper, like in my last comment?

**Comment by bertho-zero** [comment] 2019-12-06 15:56
@gregberge The generated code can create the object first and then assign functions thereafter to not use this.

```js
var HomeContainerLoader = {
  resolved: {},
  chunkName: function chunkName() {
    return "home";
  },
  importAsync: function importAsync() {
    return Promise.resolve(/*! import() | home */).then(__webpack_require__.bind(null, /*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx"));
  },
  resolve: function resolve() {
    if (true) {
      return /*require.resolve*/(/*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx");
    }

    return eval('require.resolve')("./pages/HomeContainer/HomeContainer.page");
  }
};

HomeContainerLoader.isReady = function isReady(props) {
  var key = HomeContainerLoader.resolve(props);

  if (HomeContainerLoader.resolved[key] === false) {
    return false;
  }

  if (true) {
    return !!__webpack_require__.m[key];
  }

  return false;
};

HomeContainerLoader.requireAsync = function requireAsync(props) {
  var key = HomeContainerLoader.resolve(props);
  HomeContainerLoader.resolved[key] = false;
  return HomeContainerLoader.importAsync(props).then(function (resolved) {
    HomeContainerLoader.resolved[key] = true;
    return resolved;
  });
};

HomeContainerLoader.requireSync = function requireSync(props) {
  var id = HomeContainerLoader.resolve(props);

  if (true) {
    return __webpack_require__(id);
  }

  return eval('module.require')(id);
};
```

**Comment by lfantone** [comment] 2019-12-06 16:27
I'm using like this:

```js
import { asyncComponent } from '@before.js/client';
import loadable from '@loadable/component';

const Placeholder = () => <div>Loading</div>;

const HomeContainerLoader = /* #__LOADABLE__ */ () =>
  import(/* webpackChunkName: "home" */ './pages/HomeContainer/HomeContainer.page');

export default [
  {
    path: `/`,
    exact: true,
    component: asyncComponent({
      LoadableComponent: loadable(HomeContainerLoader, { fallback: Placeholder })
    })
  }
```

The result of `loadable()` is being used in a wrapper component, that could be causing this error.

**Comment by theKashey** [comment] 2019-12-06 20:50
```js
var HomeContainerLoader = (function() {
 function chunkName() {
    return "home";
  },
  function isReady(props) {
    if (true) {
      return !!__webpack_require__.m[resolve(props)];
    }

    return false;
  },
  function requireAsync() {
    return Promise.resolve(/*! import() | home */).then(__webpack_require__.bind(null, /*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx"));
  },
  function requireSync(props) {
    var id = resolve(props);

    if (true) {
      return __webpack_require__(id);
    }

    return eval('module.require')(id);
  },
  function resolve() {
    if (true) {
      return /*require.resolve*/(/*! ./pages/HomeContainer/HomeContainer.page */ "./src/pages/HomeContainer/HomeContainer.page.jsx");
    }

    return eval('require.resolve')("./pages/HomeContainer/HomeContainer.page");
  }

return {
  chunkName,
  isReady,
  requireAsync,
  resolve,
}
})();
```
Plus we could not export some "internal" stuff, but that would be a breaking change.

**Closed** 2020-02-11 21:28 UTC
Labels: wontfix

**Comment by theKashey** [comment] 2020-02-21 08:36
Anyway - #471
