### ISSUE TITLE
Overriding loadable library methods.

### ISSUE THREAD

**Issue by fatemab** [gregberge/loadable-components#367] opened 2019-06-17 21:15 UTC
## 💬 Questions and Help

Hi,
I need an advice for using public path with my current code style.
I don't have a common public path directly available which I can pass to loadable chunk extractor. 
The issue is we pass a whole object of local bundles to server where it generates different public paths for different split bundles and sends us an asset file containing bundle names mapped with their public url.
So to make loadable work I have Override the `resolvePublicUrl` method of loadable  `ChunkExtractor.js` file 
![Screen Shot 2019-06-17 at 2 12 50 PM](https://user-images.githubusercontent.com/16335740/59637223-1e908900-910a-11e9-831c-1ada460411fe.png)
with below code :
```
  extractor.resolvePublicUrl = function (filename) {
        return publicUrlMapObject[filename];
  }
```

This code is working.

So my question is that -  Is it fine to override loadable method or there is another way out for this situation? Thank you

**Comment by theKashey** [comment] 2019-06-17 21:39
1. There are better ways to override something - inheritance
2. Even if the method name is `resolvePublicUrl` - it's __not public__, and could be changed at any time.
3. Partially duplicate of https://github.com/smooth-code/loadable-components/issues/365

**Comment by fatemab** [comment] 2019-06-18 17:36
@theKashey can you provide any other solution for my issue. How can I pass different public paths for different bundles?

**Comment by theKashey** [comment] 2019-06-18 23:32
AFAIK - there is no documented way yet.

**Closed** 2020-01-16 21:18 UTC
Labels: question ❓, wontfix
