### ISSUE TITLE
Ref is not working in Loadable Component

### ISSUE THREAD

**Issue by hashweather** [gregberge/loadable-components#861] opened 2021-12-12 19:34 UTC
## 🐛 Bug Report

I can confirm that ref is not working when loading a component
## To Reproduce
```
 const currentPageRef = useRef();
 const loadPage = (page='home') => {
        const CurrentPlatformPage = loadable(() => import(`./${page}`));
        return (
            <CurrentPlatformPage
                ref={currentPageRef}  //Ref is always null after this
             />
        );
} 

```
If however I load the page normally like this
```
import HomePage from './home';
....
return <HomePage ref={currentPageRef/> //Ref works perfectly fine


```## Expected behavior

When a component is loaded, the ref pointing to it should never be null.

**Comment by theKashey** [comment] 2021-12-12 22:54
Duplicate of #857

**Closed by theKashey** 2021-12-12 22:54 UTC
