### ISSUE TITLE
Hydrates to empty html instead of server rendered html

### ISSUE THREAD

**Issue by Pranab16** [gregberge/loadable-components#844] opened 2021-10-08 07:08 UTC
## 🐛 Bug Report

When we are using SSR, Loadable replaces it with fallback HTML during hydration. This is causing empty div at the time of hydration and then client side re-renders the whole HTML. Instead, it should not replace server rendered HTML.

## To Reproduce

I have created codesandbox to reproduce it easily. Please take a look: https://codesandbox.io/s/wizardly-bush-fwsmy

## Expected behavior

During hydration, it should render SSR HTML as is instead of fallback HTML

**Comment by asifrahman001** [comment] 2021-11-23 14:43
I am also facing the same issue. This is causing blank intermediate screen when my page is server side rendered.
Any update on issue?

**Comment by theKashey** [comment] 2021-11-23 22:34
Given example is a little invalid. Not like it just broken (it is), but `loadable` needs it's `@loadable/server` part and special meta tags injected in the header, which are missing right now.

**Comment by asifrahman001** [comment] 2021-11-24 05:37
@theKashey `@loadable/server` part is already implemented. Can you specify which meta tags are required for this. Because, I didn't find any description about meta tags in the official doc.

**Comment by asifrahman001** [comment] 2021-11-24 05:39
@Pranab16 Were you able to find any fix for this?

**Comment by Pranab16** [comment] 2021-11-24 07:02
@asifrahman001 In my case, I was doing `loadable` for pages and then inside components as well. At the time of hydration, `Loadable` only hydrates top level `loadable` pages and not the child components.
I had to move on in the favor of react 18 lazy and will wait for it's launch.

**Comment by theKashey** [comment] 2021-11-24 09:37
@asifrahman001 - __LOADABLE_REQUIRED_CHUNKS__ and __LOADABLE_REQUIRED_CHUNKS___ext
https://github.com/gregberge/loadable-components/blob/9b34195627c65372a7c834311c32dfcbd5b7fedd/packages/server/src/ChunkExtractor.test.js#L69

They indicate for which scripts loadable should wait before trying to render a component.

**Comment by ashishdocforce** [comment] 2021-12-28 07:30
Anyone found any solution for this problem yet?

**Comment by AlyonaPianykh** [comment] 2022-02-21 21:35
@theKashey Hello! Any updates on this issue?

**Comment by anthonydeguzman** [comment] 2022-05-08 16:23
I had this issue recently with react-router. It was caused by having the most top level component (my routes) rendered with loadable component. That component should be imported normally then you can use loadable components for sub components, pages, etc.

**Comment by theKashey** [comment] 2022-05-08 23:32
This is not an issue with "loadable-components", this is how React/Suspense/Your application is working.
And there is no such thing as _"That component should be imported"_. No, there are no such restrictions or rules.

**Comment by theKashey** [comment] 2022-05-08 23:32
This is not an issue with "loadable-components", this is how React/Suspense/Your application is working.
And there is no such thing as _"That component should be imported"_. No, there are no such restrictions or rules.

**Closed** 2022-08-13 05:34 UTC
Labels: wontfix

**Comment by lizijie123** [comment] 2022-10-22 12:06
> @asifrahman001- **LOADABLE_REQUIRED_CHUNKS**和 __LOADABLE_REQUIRED_CHUNKS___ext
> 
> https://github.com/gregberge/loadable-components/blob/9b34195627c65372a7c834311c32dfcbd5b7fedd/packages/server/src/ChunkExtractor.test.js#L69
> 
> 它们指示在尝试渲染组件之前应等待哪些可加载脚本。

This is correct for me
