### ISSUE TITLE
React 17 + 18 support

### ISSUE THREAD

**Issue by apepper** [gregberge/loadable-components#718] opened 2021-03-10 11:10 UTC
Currently `@loadable/component`  only supports react 16 is supported:

https://github.com/gregberge/loadable-components/blob/cba6cab47536e23ded8bac34ee24417e6452344e/package.json#L54-L55

It would be great, if it would also support [React 17](https://reactjs.org/blog/2020/10/20/react-v17.html) and the latest React 18.

**Comment by apepper** [comment] 2021-06-03 07:08
This is not stale. React 17 is still not supported:

https://github.com/gregberge/loadable-components/blob/73b17fd067579b1c5d38eba00e157964e0930a94/package.json#L54-L55

**Comment by partoneplay** [comment] 2021-06-18 05:42
I use react@17.0.2 and @loadable/component@5.15.0. They work well.

**Comment by azangru** [comment] 2021-07-11 22:52
They work, but it shows a dependency conflict when installing packages with npm 7:

![image](https://user-images.githubusercontent.com/6834224/125212068-ca354480-e2a2-11eb-829a-5bb3d523a70f.png)

Please fix this 🙏

**Comment by IPRIT** [comment] 2021-11-05 20:58
Still relevant

**Comment by IPRIT** [comment] 2022-04-17 22:33
1️⃣7️⃣

**Comment by theKashey** [comment] 2022-04-18 01:42
1️⃣8️⃣

**Comment by mike-parkhomenko** [comment] 2022-05-04 11:08
Hey! Is it possible to let us know approximately date for the next release with React 17,18 support?

Thanks)

**Comment by abhisharkjangir** [comment] 2022-06-11 07:30
Is it supports react v18? I'm getting below error with 

- "react": "^18.1.0"
- "react-dom": "^18.1.0"
- webpack": "^5.73.0"
- "@loadable/babel-plugin": "^5.13.2",
- "@loadable/component": "^5.15.2",
- "@loadable/server": "^5.15.2",
- "@loadable/webpack-plugin": "^5.15.2",
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/21080263/173178218-db3daec4-0efa-4473-8fa3-638c247e7608.png">

**Comment by polkovnikov-ph** [comment] 2022-06-21 23:16
@abhisharkjangir No, it doesn't. The library is mostly dead for the last 2 years, except for a few fixed by @theKashey.

**Comment by azangru** [comment] 2022-06-22 07:56
Now that the React team has [stopped](https://github.com/reactjs/reactjs.org/pull/4499/files#diff-fe53b6d2b7c07165bfce8953484a8f840fe8424ab0989f0dbdc0fe851c840bf7L86) recommending loadable-components in their docs, does anyone know what the official blessed approach is? With React.lazy, webpack, server-side rendering, and all?

![image](https://user-images.githubusercontent.com/6834224/174975403-11fd9fc6-14dd-41f0-8586-ad87216b8d4f.png)

**Comment by polkovnikov-ph** [comment] 2022-06-22 13:26
React 18 is a frontend library, it can't collect a list of dynamic imports that were `await`ed for during SSR. You can't do it with loadable components anymore, because it's incompatible. You can't do it with Vite SSR in dev mode, because it uses ESM and you can't hook calls to `require` there. I don't think there is any solution at the moment that actually works and might be used in production.

**Comment by theKashey** [comment] 2022-06-22 23:30
There is no recommended way of doing this and the majority of libraries(or react itself) are not working one way or another due to different reasons.
- the example from Dan will break on any ContextAPI update - https://github.com/facebook/react/issues/22692
- default examples from Loadable Components are failing since 16.10 due to change in Suspense - now you __have__ to use it on server-side (before it will generate a problem)
  - non Suspense-based usage of Loadable-component is working

**Comment by vaukalak** [comment] 2022-09-12 18:10
@abhisharkjangir  I've created [an example](https://github.com/vaukalak/loadable-components) of usign `loadable-components` with react 18. It might be, that you were facing the same hydration issue before, due to differences in your server and client generated HTML. However now, with react 18 this actually creates an error, rather than just logging the warning.

**Comment by abhisharkjangir** [comment] 2022-09-13 06:12
@vaukalak Thanks, I'll try if it works for me or not.

**Comment by fivethreeo** [comment] 2022-10-27 01:54
React 18 with Suspense would be better if chunkextractor could have a reset method. Then we could use a custom writable in renderToPipeableStream that wrote the discovered components script tags as we render. 

But loadableReady in the client cannot be used anymore so maybe write some script tags that say which modules will be loaded  from those async script tags so we don’t try to refetch those during hydration. 

If I understand all this correctly.

https://github.com/reactwg/react-18/discussions/114

https://github.com/brillout/react-streaming#injecttostream

**Comment by santicalvo** [comment] 2022-11-14 10:08
Hello, I see there is a _next release_ tag  in this issue.

Is there a roadmap or a release date scheduled? Any branch for development?

Thanks a lot for this library!

**Comment by fivethreeo** [comment] 2022-11-15 19:16
So decided to not use 

https://github.com/brillout/react-streaming#injecttostream

Instead I did this

```js

  let didError = false;
  let shellReady = false;

  class LoadableWritable extends Writable {
    constructor(writable) {
      super();
      this._writable = writable;
    }

    _write(chunk, encoding, callback) {
      // This should pick up any new link tags that hasn't been previously
      // written to this stream.
      if (shellReady) {
      }
      // Finally write whatever React tried to write.

      this._writable.write(chunk, encoding, callback);
    }

    end() {
      this._writable.end()
    }

    flush() {
      if (typeof this._writable.flush === 'function') {
        this._writable.flush();
      }
    }
  }

  const writeable = new LoadableWritable(res)

  const stream = renderToPipeableStream(<Html assets={{}}><App /></Html>,
    {
      onShellReady() {
        // The content above all Suspense boundaries is ready.
        // If something errored before we started streaming, we set the error code appropriately.
        res.statusCode = didError ? 500 : 200;
        res.setHeader('Content-type', 'text/html');
        shellReady = true;

        stream.pipe(writeable);

      })
```

https://github.com/fivethreeo/loadable-components-react-18

Will try adding loadabe-components soon

Clone and run

```shell
pnpm i
pnpm start
```

**Comment by fivethreeo** [comment] 2022-11-16 00:21
Tried adding loadable components with streaming react and suspense. Did not work.

**Comment by fivethreeo** [comment] 2022-11-17 16:20
Added support for streaming rendering here but does not allow props in ctor. 

Has two bugs:
* Stream is written to after end.
* Hydration fails, but I think that is just a ssrSuspense option being lost somewhere.

https://github.com/fivethreeo/loadable-components/tree/feature/streaming-ssr/examples/streaming-server-side-rendering

**Comment by dglozic** [comment] 2023-01-26 16:54
Any outlook for React 18 support in the near future?

**Comment by theKashey** [comment] 2023-01-27 03:05
There is "real" React 18 support in works - https://github.com/gregberge/loadable-components/pull/923, but I don't see any reason not to update package dependencies right away...

**Comment by dglozic** [comment] 2023-01-27 12:14
I agree - people can upgrade to 18 and get the current code to work, while deferring the use of `renderToPipeableStream` and suspense until it is supported by loadable components.

**Closed** 2023-01-28 04:28 UTC
Labels: next release

**Comment by theKashey** [comment] 2023-01-28 04:30
v`5.15.3` has react dependency version changed
- from 
  - `"react": ">=16.3.0"`, which should work
- to
  - `"react": "^16.3.0 || ^17.0.0 || ^18.0.0"`, which definitely works and more common in the ecosystem

**Comment by TwisterMc** [comment] 2023-08-23 17:27
Did this happen? I don't see a v 5.15.3 in the releases and v5.16.0 says `"react": "^16.12.0"`

**Comment by chidev** [comment] 2023-08-29 21:41
> I agree - people can upgrade to 18 and get the current code to work, while deferring the use of `renderToPipeableStream` and suspense until it is supported by loadable components. Actually, no, they can (and must) use it as `renderToNodeStream` is buffered in 18, but we can continue to render the App portion using `renderToString` while collecting loadables in SSR until full support is available.

Any idea how we can get React 18 and Loadable to work correctly? Just some general steps / direction would be greatly appreciated.

**Comment by dglozic** [comment] 2023-08-29 22:00
We are using Loadable just fine in React 18, what's the issue?

**Comment by azangru** [comment] 2023-08-30 07:37
> We (IBM) are currently using the latest loadable-components with React 18.2 and Loadable works fine (we are doing as explained above - rendering the App porting using renderToString, collecting loadables in SSR and then rendering the envelope using renderToPipeableStream).

Any reason why you prefer this over React.lazy?

**Comment by dglozic** [comment] 2023-08-30 11:14
SSR. We use Loadable since React16 and needed it for server side rendering. For the client side, Lazy is fine. Obviously React has this new approach for SSR in 18 with Suspense and Server Only components but this is still early and they apparently let the likes of Next.js and Remix to take the lead and define what SSR should look like with Suspense. We are waiting for that dust to settle and continuing to use Loadable as explained above.

**Comment by theKashey** [comment] 2023-08-30 21:58
Unfortunately using Lazy, or better to say - relying on Suspense does not work in many case. 
The problem is - any update to the context above Suspense will trigger it into loading mode, so you will lose not yet hydrated content - https://github.com/facebook/react/issues/22692

That's it - your app is expected to be "dead" until hydration is complete and `loadableReady` is a way to understand when it's the right time to move forward.

This is not a "code splitting" library, this is "code tracking" library. That something Lazy does not do

**Comment by salihovdr** [comment] 2024-02-29 23:00
> We are using Loadable just fine in React 18, what's the issue? We (IBM) are currently using the latest loadable-components with React 18.2 and Loadable works fine (we are doing as explained above - rendering the App porting using `renderToString`, collecting loadables in SSR and then rendering the envelope using `renderToPipeableStream`).

Can you share a basic example in code? Really curious about this part: "rendering the App porting using `renderToString`, collecting loadables in SSR and then rendering the envelope using `renderToPipeableStream`).
"

**Comment by salihovdr** [comment] 2024-03-01 02:10
@dglozic is that an internal company solution or was is based on an existing blueprint? I've been looking into using `renderToPipeableStream ` without next.js and Google led me to this thread.

**Comment by dglozic** [comment] 2024-03-01 02:14
It is internal, yes. But it is not hard to reproduce. It is also kind of interim because some proposals to support stats with streaming didn't yet make it into loadable-components (hence the initial render to a buffer to get the stats computed the old way). I keep hoping that @fivethreeo has put together would get merged :-).

**Comment by salihovdr** [comment] 2024-03-01 02:17
Gonna take a look at that example. Thank you!
