### ISSUE TITLE
Loadable components and not having dynamic imports on server

### ISSUE THREAD

**Issue by Tarvald** [gregberge/loadable-components#480] opened 2019-12-10 16:13 UTC
Hi,
I have implemented loadable components on the client and now I am building SSR instance. 

Can I have somehow to act loadable() function as a normal import?

In class constructors, I have code what has to be executed only on the server but it hasn't to be executed on the client on app init.

**Comment by theKashey** [comment] 2019-12-10 20:23
Try to wrap environment-specific with something like `if (process.env.IS_SERVER)` and defining this constant in webpack config - it would be removed on client.

**Comment by Tarvald** [comment] 2019-12-11 08:19
Is it possible to have normal imports after if statement? I guess not ;(

**Comment by theKashey** [comment] 2019-12-11 08:59
are you are talking about normal imports? How it's related to `loadable` then?

**Comment by Tarvald** [comment] 2019-12-11 13:16
@theKashey 
I would like to "loadable" some components on clients if they using CRA and normal imports on the server.

We use SSR only for initial rendering, then user are using normal CRA app :)

**Comment by theKashey** [comment] 2019-12-11 13:26
Loadable does this magic via babel plugin - it will convert  `import` to  a `require`, and synchronously  `require`  file when asked.
Not statically import, but just do it in an SSR-friendly  way.

**Comment by oreqizer** [comment] 2019-12-15 13:11
This — I need it to convert to static `import` for SSR with `urql`

**Comment by oreqizer** [comment] 2019-12-15 13:26
@Tarvald do this in the meantime:

```js
const webpack = require("webpack");
const reactizer = require("@reactizer/webpack");
const merge = require("webpack-merge");

module.exports = mode => {
  if (mode === "production") {
    return merge(reactizer(mode), {
      // Needed for fetching data during SSR
      // @loadable just converts `import()` to `require()`, not static `import`
      // https://github.com/gregberge/loadable-components/issues/480
      plugins: [new webpack.NormalModuleReplacementPlugin(/.*\/Routes.tsx$/, "./RoutesAsync.tsx")],
    });
  }

  return reactizer(mode);
};
```

and have two files — one `Routes.tsx` with static import/export, another `RoutesAsync.tsx` using `@loadable`. I use the static one in development and in Node, and async one in production client

Works 10/10

**Comment by theKashey** [comment] 2019-12-15 22:08
I would call `Routes`/`AsyncRoutes` an antipattern - it leads to the maintenance hell. Please never use this sort of separation.

`loadable` uses babel plugin to convert __dynamic__ `import` to __synchronous__ `require` for the server, and that's all you need.

Please keep in mind that today __any import__ would be also converted to a `require` to be executed in `nodejs` environment, so there is no such thing as "I need static imports".

Please also keep in mind, that there are 2 types of "dynamic imports" - the ones which are synchronous, but not executed unless required (`require`). And the ones, which are async.
If you need some code to be executed before it's actually required - please try to handle it in some other way. 

And probably you are looking for that _another_ way, which is missing in the last version. The problem comes from the _full dynamic import_ feature, or the ability to use `props` to import some stuff. That said - in some case you can not import anything without `props` provided, which ends like - __you can not import anything before the use__. By design. Even if you are not using this feature.

What I could propose in this case? Just create one more file, where you will _statically import_ all the files you are importing _dynamically_ in other places, and import that file somewhere at your server code. Still not good from the maintenance point of view, but probably is what you need - have some code executed before the use.

**Comment by oreqizer** [comment] 2019-12-16 09:05
> I would call `Routes`/`AsyncRoutes` an antipattern

I agree — it's dirty and it is the _very_ last resort. That's why I put a comment there.

However, when I do
```js
import loadable from "@loadable/component";

export const Index = loadable(() => import("app/pages/Index"));
```

then `urql`'s SSR doesn't work (it uses React's suspense and its own promise collector), so I had no other choice

**Comment by theKashey** [comment] 2019-12-16 09:10
Well, could you shed some like on "how" it's not working? Is it not working only the first time, or every time? There should be a root cause, and it has to be found.

**Comment by oreqizer** [comment] 2019-12-16 14:33
It never works. `urql` works by doing a pre-render using their own `Suspense` implementation and gathering promises, then resolving them and hydrating server data

the data gathering nor the actual render work, saying that ReactDOM doesn't support `Suspense`. when I import statically, it works. I have the `@loadable` babel plugin set up correctly

**Comment by theKashey** [comment] 2019-12-16 20:23
So what it is rendering instead? Should be something.
It's more about - loadable should not "exists" on during SSR - it should behave like it's a normal component.

**Comment by oreqizer** [comment] 2019-12-17 12:32
it's rendering correctly, but `urql`'s promises thrown during render to await are not being collected

**Comment by theKashey** [comment] 2019-12-17 12:36
Not thrown, not collected or not awaited?
I am just trying to understand what is broken to undertand how to fix it.

**Comment by oreqizer** [comment] 2019-12-17 12:37
yes thrown, not collected and thus not awaited

**Comment by theKashey** [comment] 2019-12-17 12:40
Then they would break the application. But something is stopping them from bubbling from the renderer?

**Comment by oreqizer** [comment] 2019-12-17 12:43
**what happens:**
promises are thrown, but not collected with https://github.com/formidablelabs/react-ssr-prepass

**expected behavior:**
promises thrown get collected with https://github.com/formidablelabs/react-ssr-prepass

**Comment by theKashey** [comment] 2019-12-17 12:49
Sounds like we should ask `react-ssr-prepass`. They might know the root cause.

**Comment by oreqizer** [comment] 2019-12-18 06:23
moved here https://github.com/FormidableLabs/react-ssr-prepass/issues/27

**Comment by khmm12** [comment] 2020-01-12 09:16
It works if not to forget to wrap your application tree with `extractor.collectChunks`.

```js
await ssrPrepass(
  extractor.collectChunks(
    <Root />
  )
)
```

loadable-components detects server-side environment and synchronously loads module only when extractor is given by context. The context is created inside `collectChunks`.

The main rule of all _prehydration_ strategies to have the similar application tree as inside `renderToString`.

I don't want to argue why `collectChunks` does it implicitly. You know styled-components also does the similar thing with `collectStyles`. If you forget to wrap with `collectStyles` on prehydration step, you get styles and memory leak, because `styled-components` writes stylesheets to global cache in absence of the context is given by `collectStyles`.

**Comment by oreqizer** [comment] 2020-01-12 10:42
omg @khmm12 thanks! fixed

**Closed** 2020-01-12 20:44 UTC

**Comment by heath-freenome** [comment] 2021-01-08 17:52
> @oreqizer
> 
> It works if not to forget to wrap your application tree with `extractor.collectChunks`.
> 
> ```js
> await ssrPrepass(
>   extractor.collectChunks(
>     <Root />
>   )
> )
> ```
> 
> loadable-components detects server-side environment and synchronously loads module only when extractor is given by context. The context is created inside `collectChunks`.
> 
> The main rule of all _prehydration_ strategies to have the similar application tree as inside `renderToString`. You will have the same issue if you use apollo `getDataFromTree` without `collectChunks`.
> 
> I don't want to argue why `collectChunks` does it implicitly. You know styled-components also does the similar thing with `collectStyles`. If you forget to wrap with `collectStyles` on prehydration step, you get styles and memory leak, because `styled-components` writes stylesheets to global cache in absence of the context is given by `collectStyles`.

It seems like the documentation on the README for wants to be updated to mention the need for `extractor.collectChunks()`, no?
